config/routes.rb
MagazineApp::Application.routes.draw do

  resources :books do
    resources :pages
  end

  root :to => 'home#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author, :name, :title
  has_many :pages
  accepts_nested_attributes_for :pages, allow_destroy: true

  validates :name, :title, :author, :presence => true

  def display_errors
    self.errors.full_messages.join(', ')
  end

end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  rescue_from ActiveRecord::RecordNotFound, :with => :bad_record
  rescue_from ActiveModel::MassAssignmentSecurity::Error, :with => :parameter_errors

  protected 

  def render_json(json)
    callback = params[:callback]
    response = begin
      if callback
        "#{callback}(#{json});"
      else
        json
      end
    end
    render({:content_type => :js, :text => response})
  end

  def bad_record
    render_json({:message => "No Record Found!", :status => 404}.to_json)
  end
  
  def parameter_errors
    render_json({:errors => "You have supplied invalid parameter list.", :status => 404}.to_json)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all
    @books_list = @books.to_json(:only => [:name, :title, :author]) if @books.present?
    respond_to do |format|
      format.html # index.html.erb
      format.json { 
        #render json: @books 
        render_json(@books_list)
      }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { 
        #render json: @book 
        render_json({:status => 200, :name => @book.name, :title => @book.title, :author => @book.author}.to_json)
      }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { 
          #render json: @book, status: :created, location: @book 
          render_json({:status => 200, :message => "successfully created #{@book.name} book"}.to_json)
        }
      else
        format.html { render action: "new" }
        format.json { 
          #render json: @book.errors, status: :unprocessable_entity
          render_json({:errors => @book.display_errors, :status => 404}.to_json)
        }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :find_book, :only => [:new, :create, :show, :edit, :update]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
   @page = @book.pages.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])
    @page.book_id = params[:book_id]
    respond_to do |format|
      if @page.save
        format.html { redirect_to book_page_path(@book,@page), notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to book_page_path(@book,@page), notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end

  private
    def find_book
      @book = Book.find(params[:book_id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Author</th>
    <th></th>
    <th colspan="3">Actions</th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.name %></td>
    <td><%= book.title %></td>
    <td><%= book.author %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @book.name %>
</p>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Author:</b>
  <%= @book.author %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %> |
<%= link_to "Create Page", new_book_page_path(@book) %>

<div id="flipbook">
    <div class="hard"> 
      <center><h3><%= @book.title %></h3> </center> </br>
      <center>
      <span>
        Author : <%= @book.author %> </br>
      </span>
      <center>
    </div> 
    <div class="hard"></div>
    <% @book.pages.each do |page| %>
      <div style="padding:1px;">
        <span style="padding:5px;"><%= page.content %> </span>
      </div>
    <% end %>
    <div class="hard"></div>
    <div class="hard"></div>
</div>


<script>
$("#flipbook").turn({
    width: 600,
    height: 400,
});

</script>

app/views/home/index.html.erb
<h1> Welcome to Magazine App </h1>
<p>Create a New Book : <%= link_to "Create Book", new_book_path %></p>
<p>View Books : <%= link_to "Books", books_path %></p>

app/views/layouts/_flash_notice.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert <%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviceDemoApplication</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <!-- <script type='text/javascript' src="http://www.turnjs.com/lib/turn.min.js"></script> -->
  <%= csrf_meta_tags %>
</head>
 <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
            <%= link_to "Magazine App", root_path, :class => 'brand' %>
        <ul class="nav">
            <li><%= link_to 'Login', "#" %></li>
            <li><%= link_to 'Sign up', "#" %></li>
        </ul>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
            <div class="row">
              <div class="span12">
                <%= render "layouts/flash_notice" %>
                <%= yield %>
              </div>
            </div>
         </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for [@book, @page] do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>
<%= render :partial => "/pages/form", :locals => {:page => @page} %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Book</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.content %></td>
    <td><%= page.book_id %></td>
    <td><%= page.user_id %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>
<%= render :partial => "/pages/form", :locals => {:page => @page} %>
<%= link_to 'Back', :back %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p> <b>Content:</b> <%= @page.content %></p>

<%= link_to 'Edit', edit_book_page_path(@page) %> |
<%= link_to 'Index', books_path %> 